export const canadianCities: string[] = [
    "Toronto",
    "Airdrie",
    "Ajax",
    "Alma",
    "Amherst",
    "Baie-Comeau",
    "Barrie",
    "Beloeil",
    "Blainville",
    "Brampton",
    "Brandon",
    "Bridgewater",
    "Brossard",
    "Burlington",
    "Burnaby",
    "Calgary",
    "Cambridge",
    "Cape Breton",
    "Charlottetown",
    "Chateauguay",
    "Churchill",
    "Clarington",
    "Conception Bay South",
    "Corner Brook",
    "Cornwall",
    "Dauphin",
    "Dollard-des-Ormeaux",
    "Drummondville",
    "Edmonton",
    "Estevan",
    "Flin Flon",
    "Gatineau",
    "Grande Prairie",
    "Granby",
    "Greater Sudbury",
    "Guelph",
    "Halifax",
    "Hamilton",
    "Humboldt",
    "Joliette",
    "Kamloops",
    "Kelowna",
    "Kentville",
    "Kitchener",
    "Kingston",
    "Lachute",
    "Langley",
    "Laval",
    "Levis",
    "Lethbridge",
    "Lloydminster",
    "London",
    "Longueuil",
    "Magog",
    "Maple Ridge",
    "Markham",
    "Martensville",
    "Mascouche",
    "Matane",
    "Medicine Hat",
    "Melfort",
    "Milton",
    "Mirabel",
    "Mississauga",
    "Mont-Tremblant",
    "Montmagny",
    "Montreal",
    "Moose Jaw",
    "Mount Pearl",
    "Nanaimo",
    "New Glasgow",
    "Newmarket",
    "North Battleford",
    "Oakville",
    "Oshawa",
    "Paradise",
    "Peterborough",
    "Port-Cartier",
    "Portage la Prairie",
    "Prince Albert",
    "Quebec City",
    "Red Deer",
    "Regina",
    "Repentigny",
    "Richmond",
    "Richmond Hill",
    "Rimouski",
    "Rouyn-Noranda",
    "Saanich",
    "Saguenay",
    "Saint-Eustache",
    "Saint-Georges",
    "Saint-Hyacinthe",
    "Saint-Jean-sur-Richelieu",
    "Saint-Jerome",
    "Saint-John",
    "Saint-John's",
    "Saint-Therese",
    "Sainte-Julie",
    "Sainte-Therese",
    "Saskatoon",
    "Selkirk",
    "Sept-Iles",
    "Sherbrooke",
    "Sherwood Park",
    "Spruce Grove",
    "Steinbach",
    "St. Albert",
    "St. Catharines",
    "St. John's",
    "Stratford",
    "Sudbury",
    "Summerside",
    "Surrey",
    "Sydney",
    "Terrebonne",
    "The Pas",
    "Thompson",
    "Thunder Bay",
    "Trois-Rivieres",
    "Truro",
    "Val-d'Or",
    "Valleyfield",
    "Vancouver",
    "Vaughan",
    "Victoria",
    "Victoriaville",
    "Warman",
    "Waterloo",
    "Weyburn",
    "Whitby",
    "Windsor",
    "Winnipeg",
    "Winkler",
    "Yarmouth",
    "Yorkton"
];
